In [1]:
import numpy as np
import pandas as pd

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [4]:
np.arange(.5,9.5) # to generate float ranges

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5])

In [6]:
list(np.linspace(1,2,10)) # divides 1 to 2 in 10 distribution

[1.0,
 1.1111111111111112,
 1.2222222222222223,
 1.3333333333333333,
 1.4444444444444444,
 1.5555555555555556,
 1.6666666666666665,
 1.7777777777777777,
 1.8888888888888888,
 2.0]

In [7]:
list(np.linspace(1,2,10,retstep=True)) 

[array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 0.1111111111111111]

In [9]:
np.logspace(1,50,5)

array([1.00000000e+01, 1.77827941e+13, 3.16227766e+25, 5.62341325e+37,
       1.00000000e+50])

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [15]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
a = np.eye(5)

In [18]:
a.shape

(5, 5)

In [19]:
a.size

25

In [20]:
a.ndim

2

In [21]:
a1 = np.random.randn(3,4)

In [22]:
a1

array([[ 1.29271627,  0.6549127 ,  0.28895712,  0.91984598],
       [ 1.08788792,  0.33417013,  1.56963824, -1.70168821],
       [-1.33523412,  1.06168521,  0.83699709, -0.44518884]])

In [23]:
pd.DataFrame(a1)

0         1         2         3
0  1.292716  0.654913  0.288957  0.919846
1  1.087888  0.334170  1.569638 -1.701688
2 -1.335234  1.061685  0.836997 -0.445189

In [24]:
a1

array([[ 1.29271627,  0.6549127 ,  0.28895712,  0.91984598],
       [ 1.08788792,  0.33417013,  1.56963824, -1.70168821],
       [-1.33523412,  1.06168521,  0.83699709, -0.44518884]])

In [27]:
a1[0:2,0:2]

array([[1.29271627, 0.6549127 ],
       [1.08788792, 0.33417013]])

In [31]:
a1[[1,2],3]

array([-1.70168821, -0.44518884])

In [47]:
m1 = np.random.randint(1,3,(3,3))

In [48]:
m2 = np.random.randint(2,4,(3,3))

In [49]:
m1

array([[2, 1, 1],
       [1, 1, 2],
       [1, 1, 2]])

In [50]:
m2

array([[2, 3, 2],
       [2, 2, 2],
       [3, 3, 3]])

In [51]:
m1 * m2  # element wise multiply

array([[4, 3, 2],
       [2, 2, 4],
       [3, 3, 6]])

In [52]:
m1 @ m2 # matrix multiplication

array([[ 9, 11,  9],
       [10, 11, 10],
       [10, 11, 10]])

In [53]:
pow(m1,4)

array([[16,  1,  1],
       [ 1,  1, 16],
       [ 1,  1, 16]], dtype=int32)

In [54]:
np.sqrt(m1)

array([[1.41421356, 1.        , 1.        ],
       [1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.41421356]])

In [55]:
np.log(m1)

array([[0.69314718, 0.        , 0.        ],
       [0.        , 0.        , 0.69314718],
       [0.        , 0.        , 0.69314718]])

In [56]:
np.exp(m1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [57]:
m1**2

array([[4, 1, 1],
       [1, 1, 4],
       [1, 1, 4]])